version: "3"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "123123"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "root"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
  php:
    image: my-php-app
    volumes:
      - ./src/:/var/www/html:ro
  web:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx/:/etc/nginx/conf.d
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8082:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]